language: rust
rust:
  - stable
  - beta
  - nightly
  # minimum supported version
  - "1.19.0"
matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo build
  - cargo test --all
  - tests/run.sh

after_success:
  - |
    [ ! $TRAVIS_BRANCH = master ] ||
    [ ! $TRAVIS_RUST_VERSION = stable ] ||
    ci/doc-upload.sh

env:
  global:
    - secure: "SjFTsn1KuFWw0huk6fFyYfwqhaICBLfx8P8RnnKwhR3AFJ8CKYux8O+fbHCPMo/4Q5YG9/0PUNAiFbKuEtgZsEoitG4LpBG7abSzgDHJWuuE6s8c22hWiQzz0qU86swRD+DdvBiaJGcBUg3TRnSZ5HEalwctOxeldTMH9gP04XYXZMlOxaRb/STIHeWyMuo76lb4SGehgftidDO4B9SSBYSmH6ipLdSW8o/01MP25Q0nRWvzaC8pJcNLplxt1ILm1n6bjxftlwZhagrHlGsJY4ngpJgsfj3L+0Jq9iL/yBsmPddnR+kimzUDRmx1xhs7bDkgE955Go2NM+gswthZ77XyfAzN6yi90hTCyruyl/AHm0MRkkD2ubkT+gVdD0iV3X8RiJZhGi9F2QHLbLIqvVLVyQfXcB0uEvL77dfnRaqxwWl5mGSfIwVKKFDm0F7YhZ8KE8JAB/9bTWS8ysXzrzXhqdO0sxTZCjDLDEKnxpAH4oCGAdu0W6Nb4iQulFJkepdc9vTDdt4Tb6rfA8B7mBtZqqQoFSJPifJ0ETdYS7SpziH90Ch4yrE9tvia+WKGL5UbLbXZ3z5fTQh1VFgC5Ib33X7JBmkcXE8qGH/4mu6Cshw/toL/42buu8DmtT3H877k6scW/AYeMq83C7BJJ2J36D4M75CxMEWfSU6pIfE="

notifications:
  slack:
    secure: "ON5mSYxG4Tlmpmn+g+/qL43z1IrYDvVTmaId/I8Hlcw4UN7VSgNybefEBf1wnmPz73C8/8/jfJWXfAFMDDvKx05OZy3dZv4wMhxH3vufrjdyOVcjMbWPTzNpzrTMnDfGoegVI1TYM5AoXpRbrKHvxne0T7qVWn/hNE0ZufLniGT5JgjHR3e825Jw1/zZB3XFBqI5tP8EmilDVLqtDJXI4wNsA5tk4M1aQLKqKrlhvbNgG60rsnwe/RTkc/DKAsfOFyTEg9518zPZnUAKV7zbTWll8F5Fr9PLyV4c1EWyanEi1g1ZarS+4t7zYkHr+PMvcOehadEEAYqafmoMTowIN+MB3/uCMLWUXP4dIgSTim/vjygr/RfBTRkYPLtqeCphdqoz0GnTOHqDVxkXvQYlspojF/7/L6MToE0YdiWd2X7XM8JqW/2Qsmn8EjOo8/HO2zJyUVcigE+oi9+dkbBm7MEZ7R6zIxa1MNTIGttd6lSRLUh9xia1uejV2PRWxINhfb0/Nrr4gw1SKwCq38VjbAth88smd5EZf4ukajO+qdXvBC5OmzL0lrEpj+A53DNzmRVRK+6MLAFLfJ/h4SSQ0itzqy11CSVNOfqgTlpojz2c1FNgZ/bKVXsHkpFyA/K9vrz9/yUip0n9fW2yFcEBnER4J2/jWIGW5hTEuPvDhQM="
