language: rust
# cache: cargo
rust:
  - stable
  - beta
  - nightly
  # minimum supported version
  - "1.38.0"
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script:
  - rustup component add rustfmt

script:
  - "[ $TRAVIS_RUST_VERSION != stable ] || cargo fmt -- --check"
  - cargo build
  - cargo test --all
  - test/run.sh
  - python3 scripts/test.py --debug --verbose
